### ISSUE TITLE
🚗 Brakeman Scanning failing

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/network-access-control-admin#608]
[Brakeman Analysis](https://github.com/ministryofjustice/network-access-control-admin/actions/workflows/brakeman-analysis.yml) is failing.

Rectify or remove. 

```
This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
```

**Comment by ASTRobinson** [comment]
Dependabot updated to include GitHub Action dependencies. moved to review awaiting the generation of a new PR
